# Generated by Django 2.0.7 on 2018-07-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('price_point', models.CharField(blank=True, choices=[('$', 'Cheap'), ('$$', 'Moderate'), ('$$$', 'Pricey')], help_text='Price Range', max_length=3)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='picker.Location')),
            ],
        ),
    ]
